/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { UtecMetric, EducationalUnit } from './types';

export const INITIAL_UTECS: UtecMetric[] = [
  {
    id: 'utec-1',
    name: 'UTEC BOA VIAGEM',
    regional: 'Regional 1',
    unidades: 2,
    estudantes: 1488,
    lct: 2,
    rob: 1,
    cine: 1,
    fcd: 2,
    rev: 1,
    coordinator: 'Mariana Guimarães',
    email: 'mariana.utec1@recife.pe.gov.br',
    phone: '(81) 98122-3041',
    status: 'Ativa',
    creationDate: '2023-03-15',
  },
  {
    id: 'utec-2',
    name: 'UTEC JARDIM BOTANICO',
    regional: 'Regional 2',
    unidades: 2,
    estudantes: 1958,
    lct: 2,
    rob: 1,
    cine: 1,
    fcd: 2,
    rev: 0,
    coordinator: 'Carlos Alberto Souza',
    email: 'carlos.utec2@recife.pe.gov.br',
    phone: '(81) 98144-5022',
    status: 'Ativa',
    creationDate: '2022-08-10',
  },
  {
    id: 'utec-3',
    name: 'UTEC SITIO TRINDADE',
    regional: 'Regional 3',
    unidades: 2,
    estudantes: 1485,
    lct: 2,
    rob: 1,
    cine: 1,
    fcd: 2,
    rev: 1,
    coordinator: 'Patrícia Albuquerque',
    email: 'patricia.utec3@recife.pe.gov.br',
    phone: '(81) 98211-4033',
    status: 'Ativa',
    creationDate: '2023-01-22',
  },
  {
    id: 'utec-4',
    name: 'UTEC SANTO AMARO',
    regional: 'Regional 4',
    unidades: 2,
    estudantes: 1535,
    lct: 1,
    rob: 1,
    cine: 2,
    fcd: 1,
    rev: 1,
    coordinator: 'Fernando Bezerra',
    email: 'fernando.utec4@recife.pe.gov.br',
    phone: '(81) 98155-2200',
    status: 'Ativa',
    creationDate: '2021-11-05',
  },
  {
    id: 'utec-5',
    name: 'UTEC GREGORIO BEZERRA',
    regional: 'Regional 5',
    unidades: 2,
    estudantes: 1582,
    lct: 2,
    rob: 1,
    cine: 0,
    fcd: 2,
    rev: 1,
    coordinator: 'Luciana Melo Santos',
    email: 'luciana.utec5@recife.pe.gov.br',
    phone: '(81) 98311-5066',
    status: 'Ativa',
    creationDate: '2024-02-18',
  },
  {
    id: 'utec-6',
    name: 'UTEC IBURA',
    regional: 'Regional 1',
    unidades: 1,
    estudantes: 820,
    lct: 1,
    rob: 2,
    cine: 1,
    fcd: 1,
    rev: 0,
    coordinator: 'Ricardo Oliveira Gomes',
    email: 'ricardo.utec6@recife.pe.gov.br',
    phone: '(81) 98711-2099',
    status: 'Ativa',
    creationDate: '2024-03-10',
  },
  {
    id: 'utec-7',
    name: 'UTEC ALTO STA TEREZINHA',
    regional: 'Regional 2',
    unidades: 1,
    estudantes: 910,
    lct: 1,
    rob: 1,
    cine: 1,
    fcd: 1,
    rev: 1,
    coordinator: 'Bruna Vasconcelos',
    email: 'bruna.utec7@recife.pe.gov.br',
    phone: '(81) 98844-3122',
    status: 'Ativa',
    creationDate: '2023-07-22',
  },
  {
    id: 'utec-8',
    name: 'UTEC CAXANGÁ',
    regional: 'Regional 3',
    unidades: 1,
    estudantes: 740,
    lct: 1,
    rob: 1,
    cine: 1,
    fcd: 0,
    rev: 1,
    coordinator: 'Tiago Mendes Silva',
    email: 'tiago.utec8@recife.pe.gov.br',
    phone: '(81) 98222-7711',
    status: 'Ativa',
    creationDate: '2022-09-05',
  },
  {
    id: 'utec-9',
    name: 'UTEC COQUE',
    regional: 'Regional 4',
    unidades: 1,
    estudantes: 680,
    lct: 2,
    rob: 1,
    cine: 2,
    fcd: 1,
    rev: 1,
    coordinator: 'Amanda Correia Costa',
    email: 'amanda.utec9@recife.pe.gov.br',
    phone: '(81) 98311-4455',
    status: 'Ativa',
    creationDate: '2023-05-14',
  },
  {
    id: 'utec-10',
    name: 'UTEC CORDEIRO',
    regional: 'Regional 5',
    unidades: 1,
    estudantes: 895,
    lct: 3,
    rob: 2,
    cine: 1,
    fcd: 2,
    rev: 1,
    coordinator: 'Rodrigo Santana Ramos',
    email: 'rodrigo.utec10@recife.pe.gov.br',
    phone: '(81) 98400-3322',
    status: 'Ativa',
    creationDate: '2022-04-18',
  },
  {
    id: 'utec-11',
    name: 'UTEC CRISTIANO DONATO',
    regional: 'Regional 1',
    unidades: 1,
    estudantes: 712,
    lct: 1,
    rob: 1,
    cine: 0,
    fcd: 1,
    rev: 1,
    coordinator: 'Cláudia Regina Silva',
    email: 'claudia.utec11@recife.pe.gov.br',
    phone: '(81) 98111-9988',
    status: 'Ativa',
    creationDate: '2024-01-20',
  },
  {
    id: 'utec-12',
    name: 'UTEC LARGO DOM LUIS',
    regional: 'Regional 2',
    unidades: 1,
    estudantes: 830,
    lct: 2,
    rob: 2,
    cine: 1,
    fcd: 1,
    rev: 0,
    coordinator: 'Marcelo Diniz Abreu',
    email: 'marcelo.utec12@recife.pe.gov.br',
    phone: '(81) 98511-0022',
    status: 'Ativa',
    creationDate: '2023-10-05',
  },
  {
    id: 'utec-13',
    name: 'UTEC NOVA DESCOBERTA',
    regional: 'Regional 3',
    unidades: 1,
    estudantes: 950,
    lct: 1,
    rob: 1,
    cine: 1,
    fcd: 2,
    rev: 2,
    coordinator: 'Vanessa Lima Cruz',
    email: 'vanessa.utec13@recife.pe.gov.br',
    phone: '(81) 98233-1144',
    status: 'Ativa',
    creationDate: '2023-02-28',
  },
  {
    id: 'utec-14',
    name: 'UTEC PINA',
    regional: 'Regional 4',
    unidades: 1,
    estudantes: 790,
    lct: 2,
    rob: 1,
    cine: 2,
    fcd: 1,
    rev: 1,
    coordinator: 'Eduardo Santos Neto',
    email: 'eduardo.utec14@recife.pe.gov.br',
    phone: '(81) 98322-8811',
    status: 'Ativa',
    creationDate: '2022-12-12',
  }
];

export const REGIONALS = [
  'Regional 1',
  'Regional 2',
  'Regional 3',
  'Regional 4',
  'Regional 5',
];

export const HELP_TOPICS = [
  { title: 'Como cadastrar estudantes?', desc: 'Acesse o menu Configurações ou clique no botão de ação rápida para integrar planilhas.' },
  { title: 'O que significa LCT?', desc: 'Laboratório de Ciência e Tecnologia para o desenvolvimento de robótica e programação.' },
  { title: 'Formatos de Relatório', desc: 'Os relatórios de acompanhamento regional podem ser exportados em PDF e planilha Excel (CSV).' }
];

const RAW_EDUCATIONAL_UNITS: EducationalUnit[] = [
  {
    inep_escola: '26019383',
    id_utec_suporte: 'utec-1',
    rpa_escola: 'RPA 1',
    endereco: 'Rua da Aurora, 451 - Boa Vista, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental I e II',
    nome_unidade: 'Escola Municipal Professor João Oliveira',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 750,
    por_demanda: 'Sim',
    qtd_lct: 2,
    qtd_cineclube: 1,
    qtd_robotica: 1
  },
  {
    inep_escola: '26027811',
    id_utec_suporte: 'utec-1',
    rpa_escola: 'RPA 4',
    endereco: 'Av. General San Martin, 500 - San Martin, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental II e EJA',
    nome_unidade: 'Escola Municipal Dom Bosco San Martin',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 738,
    por_demanda: 'Não',
    qtd_lct: 1,
    qtd_cineclube: 0,
    qtd_robotica: 2
  },
  {
    inep_escola: '26089122',
    id_utec_suporte: 'utec-2',
    rpa_escola: 'RPA 2',
    endereco: 'Estrada de Belém, 347 - Campo Grande, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental I e II',
    nome_unidade: 'Escola Municipal Severina Lira',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 980,
    por_demanda: 'Sim',
    qtd_lct: 3,
    qtd_cineclube: 1,
    qtd_robotica: 2
  },
  {
    inep_escola: '26011233',
    id_utec_suporte: 'utec-2',
    rpa_escola: 'RPA 2',
    endereco: 'Av. Beberibe, 850 - Arruda, Recife - PE',
    modalidade_ensino: 'Educação Infantil e Creche',
    nome_unidade: 'Creche Escola Municipal Recife Esperança',
    tipo_unidade: 'Creche Escola',
    qtd_estudantes: 978,
    por_demanda: 'Não',
    qtd_lct: 0,
    qtd_cineclube: 0,
    qtd_robotica: 1
  },
  {
    inep_escola: '26190412',
    id_utec_suporte: 'utec-3',
    rpa_escola: 'RPA 3',
    endereco: 'Estrada do Encanamento, 110 - Casa Forte, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental II',
    nome_unidade: 'Escola Municipal Célis Botelho',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 785,
    por_demanda: 'Sim',
    qtd_lct: 2,
    qtd_cineclube: 1,
    qtd_robotica: 1
  },
  {
    inep_escola: '26123445',
    id_utec_suporte: 'utec-3',
    rpa_escola: 'RPA 3',
    endereco: 'Rua Chacon, 215 - Poço da Panela, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental I',
    nome_unidade: 'Escola Municipal Jardim Monteverde',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 700,
    por_demanda: 'Não',
    qtd_lct: 1,
    qtd_cineclube: 1,
    qtd_robotica: 0
  },
  {
    inep_escola: '26209211',
    id_utec_suporte: 'utec-4',
    rpa_escola: 'RPA 4',
    endereco: 'Rua Benfica, 550 - Madalena, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental II e EJA',
    nome_unidade: 'Escola Municipal Cecília Meireles',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 800,
    por_demanda: 'Sim',
    qtd_lct: 2,
    qtd_cineclube: 2,
    qtd_robotica: 1
  },
  {
    inep_escola: '26289012',
    id_utec_suporte: 'utec-4',
    rpa_escola: 'RPA 4',
    endereco: 'Av. General San Martin, 1200 - San Martin, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental I e II',
    nome_unidade: 'Escola Municipal General San Martin',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 735,
    por_demanda: 'Sim',
    qtd_lct: 1,
    qtd_cineclube: 0,
    qtd_robotica: 1
  },
  {
    inep_escola: '26233441',
    id_utec_suporte: 'utec-5',
    rpa_escola: 'RPA 5',
    endereco: 'Rua João de Barros, 401 - Soledade, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental II',
    nome_unidade: 'Escola Municipal Padre Henrique',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 810,
    por_demanda: 'Não',
    qtd_lct: 2,
    qtd_cineclube: 1,
    qtd_robotica: 1
  },
  {
    inep_escola: '26299102',
    id_utec_suporte: 'utec-5',
    rpa_escola: 'RPA 5',
    endereco: 'Estrada dos Remédios, 730 - Afogados, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental Integral / ETI',
    nome_unidade: 'Escola de Tempo Integral Mangabeira',
    tipo_unidade: 'Escola de Tempo Integral',
    qtd_estudantes: 772,
    por_demanda: 'Sim',
    qtd_lct: 3,
    qtd_cineclube: 2,
    qtd_robotica: 2
  },
  {
    inep_escola: '26061122',
    id_utec_suporte: 'utec-6',
    rpa_escola: 'RPA 1',
    endereco: 'Rua do Príncipe, 526 - Recife - PE',
    modalidade_ensino: 'Ensino Fundamental I',
    nome_unidade: 'Escola Municipal de Beberibe',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 820,
    por_demanda: 'Sim',
    qtd_lct: 1,
    qtd_cineclube: 1,
    qtd_robotica: 2
  },
  {
    inep_escola: '26071133',
    id_utec_suporte: 'utec-7',
    rpa_escola: 'RPA 2',
    endereco: 'Rua Castro Alves, 82 - Encruzilhada, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental II',
    nome_unidade: 'Escola Municipal Aníbal Fernandes',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 910,
    por_demanda: 'Não',
    qtd_lct: 1,
    qtd_cineclube: 1,
    qtd_robotica: 1
  },
  {
    inep_escola: '26081144',
    id_utec_suporte: 'utec-8',
    rpa_escola: 'RPA 3',
    endereco: 'Rua Harmonia, 115 - Casa Amarela, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental I e II',
    nome_unidade: 'Escola Municipal de Casa Amarela',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 740,
    por_demanda: 'Sim',
    qtd_lct: 1,
    qtd_cineclube: 1,
    qtd_robotica: 1
  },
  {
    inep_escola: '26091155',
    id_utec_suporte: 'utec-9',
    rpa_escola: 'RPA 4',
    endereco: 'Rua Real da Torre, 630 - Madalena, Recife - PE',
    modalidade_ensino: 'Creche e Educação Infantil',
    nome_unidade: 'Creche Municipal Madalena Feliz',
    tipo_unidade: 'Creche Escola',
    qtd_estudantes: 680,
    por_demanda: 'Sim',
    qtd_lct: 2,
    qtd_cineclube: 2,
    qtd_robotica: 1
  },
  {
    inep_escola: '26101166',
    id_utec_suporte: 'utec-10',
    rpa_escola: 'RPA 5',
    endereco: 'Av. Recife, 3000 - Ipsep, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental II e EJA',
    nome_unidade: 'Escola de Tempo Integral Ipsep',
    tipo_unidade: 'Escola de Tempo Integral',
    qtd_estudantes: 895,
    por_demanda: 'Sim',
    qtd_lct: 3,
    qtd_cineclube: 1,
    qtd_robotica: 2
  },
  {
    inep_escola: '26111177',
    id_utec_suporte: 'utec-11',
    rpa_escola: 'RPA 1',
    endereco: 'Av. Cruz Cabugá, 410 - Santo Amaro, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental I',
    nome_unidade: 'Escola Municipal Santo Amaro',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 712,
    por_demanda: 'Não',
    qtd_lct: 1,
    qtd_cineclube: 0,
    qtd_robotica: 1
  },
  {
    inep_escola: '26121188',
    id_utec_suporte: 'utec-12',
    rpa_escola: 'RPA 2',
    endereco: 'Estrada de Água Fria, 905 - Água Fria, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental I e II',
    nome_unidade: 'Escola Municipal Água Fria de Lira',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 830,
    por_demanda: 'Não',
    qtd_lct: 2,
    qtd_cineclube: 1,
    qtd_robotica: 2
  },
  {
    inep_escola: '26131199',
    id_utec_suporte: 'utec-13',
    rpa_escola: 'RPA 3',
    endereco: 'Rua do Canal, 330 - Arruda, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental II',
    nome_unidade: 'Escola Municipal Governador Miguel Arraes',
    tipo_unidade: 'Escola Municipal',
    qtd_estudantes: 950,
    por_demanda: 'Sim',
    qtd_lct: 1,
    qtd_cineclube: 1,
    qtd_robotica: 1
  },
  {
    inep_escola: '26141200',
    id_utec_suporte: 'utec-14',
    rpa_escola: 'RPA 4',
    endereco: 'Av. Caxangá, 2200 - Cordeiro, Recife - PE',
    modalidade_ensino: 'Ensino Fundamental Integral',
    nome_unidade: 'Escola de Tempo Integral do Cordeiro',
    tipo_unidade: 'Escola de Tempo Integral',
    qtd_estudantes: 790,
    por_demanda: 'Sim',
    qtd_lct: 2,
    qtd_cineclube: 2,
    qtd_robotica: 1
  }
];

const GESTORES_PRESETS: { [inep: string]: { gestor: string; vice_gestor: string } } = {
  '26019383': { gestor: 'Manoel de Araújo', vice_gestor: 'Sônia Guimarães' },
  '26027811': { gestor: 'Patrícia Albuquerque', vice_gestor: 'Júlio César Santos' },
  '26089122': { gestor: 'Renata Maria Silva', vice_gestor: 'Carla Dias Medeiros' },
  '26011233': { gestor: 'Luciano Amaral Chaves', vice_gestor: 'Aline de Souza' },
  '26190412': { gestor: 'Felipe Cabral Pontes', vice_gestor: 'Mariana Duarte' },
  '26123445': { gestor: 'Clara Costa Marinho', vice_gestor: 'Edson Arantes Nobre' },
  '26209211': { gestor: 'Roberto de Oliveira', vice_gestor: 'Bianca Melo' },
  '26289012': { gestor: 'Tiago Silveira', vice_gestor: 'Fernanda Lima' },
  '26233441': { gestor: 'Beatriz Vasconcelos', vice_gestor: 'Mateus Ramos' },
  '26299102': { gestor: 'Eduardo Correia', vice_gestor: 'Amanda Sales' },
  '26061122': { gestor: 'Isabela Santos', vice_gestor: 'Vinícius Rocha' },
  '26071133': { gestor: 'Ricardo de Souza', vice_gestor: 'Letícia Guedes' },
  '26081144': { gestor: 'Gabriela Vasconcellos', vice_gestor: 'Bruno Martins' },
  '26091155': { gestor: 'Paula Albuquerque', vice_gestor: 'Rodrigo Cabral' },
  '26101166': { gestor: 'Alexandre Magno', vice_gestor: 'Teresa Cristina' },
  '26111177': { gestor: 'Juliana Paes', vice_gestor: 'Marcos Frota' },
  '26121188': { gestor: 'Daniela Mercury', vice_gestor: 'Carlinhos Brown' },
  '26131199': { gestor: 'Ivete Sangalo', vice_gestor: 'Gilberto Gil' },
  '26141200': { gestor: 'Caetano Veloso', vice_gestor: 'Maria Bethânia' },
};

export const INITIAL_EDUCATIONAL_UNITS: EducationalUnit[] = RAW_EDUCATIONAL_UNITS.map(unit => {
  const managers = GESTORES_PRESETS[unit.inep_escola] || { gestor: 'Gestor Não Cadastrado', vice_gestor: 'Vice Gestor Não Cadastrado' };
  return {
    ...unit,
    gestor: managers.gestor,
    vice_gestor: managers.vice_gestor
  };
});
